name: shem
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2
  flutter_screenutil: ^5.8.4
  get: ^4.6.6
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.7.0
  infinite_scroll_pagination: ^3.2.0
  visibility_detector: ^0.4.0+2
  modal_bottom_sheet: ^3.0.0-pre
  intl: ^0.18.0
  timeago: ^3.5.0
  url_launcher: ^6.1.12
  logger: ^2.0.1
  get_storage: ^2.1.1
  lottie: ^2.5.0
  flutter_localizations:
    sdk: flutter
  bot_toast: ^4.0.4
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  circular_color_picker: ^1.0.0
  flutter_in_store_app_version_checker: ^1.5.2
  carousel_slider: ^4.2.1
  image_picker_type: ^1.1.2
  flutter_image_compress: ^1.1.3
  path_provider:
  dots_indicator: ^3.0.0
  daum_postcode_view: ^0.1.2
  video_player: ^2.8.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
